config/routes.rb
Rails.application.routes.draw do
  resources :book_relations

  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/book_relation.rb
class BookRelation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_relations_controller.rb
class BookRelationsController < ApplicationController
  before_action :set_book_relation, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @book_relations = BookRelation.all
    respond_with(@book_relations)
  end

  def show
    respond_with(@book_relation)
  end

  def new
    @book_relation = BookRelation.new
    respond_with(@book_relation)
  end

  def edit
  end

  def create
    @book_relation = BookRelation.new(book_relation_params)
    @book_relation.save
    respond_with(@book_relation)
  end

  def update
    @book_relation.update(book_relation_params)
    respond_with(@book_relation)
  end

  def destroy
    @book_relation.destroy
    respond_with(@book_relation)
  end

  private
    def set_book_relation
      @book_relation = BookRelation.find(params[:id])
    end

    def book_relation_params
      params.require(:book_relation).permit(:user_id, :book_id, :owned, :wanted, :read)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_first_name, :author_last_name, :publisher, :isbn10, :isbn13, :book_length)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_relations_helper.rb
module BookRelationsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/book_relations/_form.html.erb
<%= form_for(@book_relation) do |f| %>
  <% if @book_relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_relation.errors.count, "error") %> prohibited this book_relation from being saved:</h2>

      <ul>
      <% @book_relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.text_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :owned %><br>
    <%= f.text_field :owned %>
  </div>
  <div class="field">
    <%= f.label :wanted %><br>
    <%= f.text_field :wanted %>
  </div>
  <div class="field">
    <%= f.label :read %><br>
    <%= f.text_field :read %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_relations/edit.html.erb
<h1>Editing book_relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_relation %> |
<%= link_to 'Back', book_relations_path %>

app/views/book_relations/index.html.erb
<h1>Listing book_relations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Owned</th>
      <th>Wanted</th>
      <th>Read</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_relations.each do |book_relation| %>
      <tr>
        <td><%= book_relation.user_id %></td>
        <td><%= book_relation.book_id %></td>
        <td><%= book_relation.owned %></td>
        <td><%= book_relation.wanted %></td>
        <td><%= book_relation.read %></td>
        <td><%= link_to 'Show', book_relation %></td>
        <td><%= link_to 'Edit', edit_book_relation_path(book_relation) %></td>
        <td><%= link_to 'Destroy', book_relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book relation', new_book_relation_path %>

app/views/book_relations/new.html.erb
<h1>New book_relation</h1>

<%= render 'form' %>

<%= link_to 'Back', book_relations_path %>

app/views/book_relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @book_relation.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_relation.book_id %>
</p>

<p>
  <strong>Owned:</strong>
  <%= @book_relation.owned %>
</p>

<p>
  <strong>Wanted:</strong>
  <%= @book_relation.wanted %>
</p>

<p>
  <strong>Read:</strong>
  <%= @book_relation.read %>
</p>

<%= link_to 'Edit', edit_book_relation_path(@book_relation) %> |
<%= link_to 'Back', book_relations_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author_first_name %><br>
    <%= f.text_field :author_first_name %>
  </div>
  <div class="field">
    <%= f.label :author_last_name %><br>
    <%= f.text_field :author_last_name %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :isbn10 %><br>
    <%= f.text_field :isbn10 %>
  </div>
  <div class="field">
    <%= f.label :isbn13 %><br>
    <%= f.text_field :isbn13 %>
  </div>
  <div class="field">
    <%= f.label :book_length %><br>
    <%= f.text_field :book_length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author first name</th>
      <th>Author last name</th>
      <th>Publisher</th>
      <th>Isbn10</th>
      <th>Isbn13</th>
      <th>Book length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author_first_name %></td>
        <td><%= book.author_last_name %></td>
        <td><%= book.publisher %></td>
        <td><%= book.isbn10 %></td>
        <td><%= book.isbn13 %></td>
        <td><%= book.book_length %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author first name:</strong>
  <%= @book.author_first_name %>
</p>

<p>
  <strong>Author last name:</strong>
  <%= @book.author_last_name %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Isbn10:</strong>
  <%= @book.isbn10 %>
</p>

<p>
  <strong>Isbn13:</strong>
  <%= @book.isbn13 %>
</p>

<p>
  <strong>Book length:</strong>
  <%= @book.book_length %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookInventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>